### ISSUE TITLE
Native deployment management of Processing Broker

### ISSUE THREAD

**Issue by tdoan2010** [OCR-D/zenhub#138]
The processing broker parses the [configuration file](https://github.com/OCR-D/zenhub/issues/137) and deploys necessary components (processors or a queuing system). The deployment of the processors is made natively (not via Docker).

This feature can be implemented in the following steps:

1. `ssh` to the specified machine using the provided credentials.
1. Assume that `ocrd-all` was installed in that machine, execute a shell command to start a processor as a consumer in the background.
1. Save the process ID (PID) of the execution.
1. Shutdown the processor later via its PID obtained earlier.

To start the processing broker, the CLI syntax would be:

```shell
$ ocrd processing-broker --address=<IP>:<PORT> <path-to-config-file>
```

After executing that command, an instance of a processing broker will be started and listen to the provided IP and port.

**Comment by tdoan2010** [comment]
* For `ssh`in Python, use [Paramiko](https://www.paramiko.org/).
* The processing server needs to be started in background. So, you can do it [like this](https://stackoverflow.com/a/59094487/1814420) to start it in background and get its PID immediately after that.

**Comment by joschrew** [comment]
Closed because it is available in ocrd_network in core
