### ISSUE TITLE
Example for general testing Steps

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#31]

**Comment by mweidling** [comment]
For on-boarding new project members, detailed steps in a MR/PR description on how to test a new feature are pretty useful. They should describe how someone with hardly any prior knowledge can execute and verify the new feature.

Example:

1. pull the branch `xyz`
2. execute the following command via CLI: `foo bar`
3. the following should happen: `asdfqwerty`

A real world example from the TIDO project: https://gitlab.gwdg.de/subugoe/emo/tido/-/merge_requests/130#tests.

**Comment by mweidling** [comment]
@paulpestov Is there something missing? :)

**Comment by paulpestov** [comment]
Seems ok to me in general. The question is whether its possible to perform local testing of the changes in a reasonable way.

**Comment by krvoigt** [comment]
@mweidling can you implement the templates please?

**Comment by mweidling** [comment]
@krvoigt Sure. I wasn't aware that this issue has been considered as "reviewed and accepted".

**Comment by mweidling** [comment]
@krvoigt Can this ticket be closed? I added a "Tests" section to the PR template.

**Comment by mweidling** [comment]
See https://github.com/OCR-D/zenhub/commit/f6dce6f699b29b8073e97f10bf87e122ba8104e2.

**Comment by mweidling** [comment]
@kba @krvoigt Since I've provided the examples I'll remove myself from the list of assignees. Feel free to re-add my if there's something I could/should do.
