### ISSUE TITLE
Reference implementation of the API

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#70]
**Describe the feature you'd like**
A reference implementation of the Web API 

**Is your feature request related to a problem? Please describe.**
no problem

**User story**
As an OCR-D implementer, I would like to see an example implementation of the API to try it out, to look at it, to make sense of it, to better understand if it is usable for my purposes, to add requirements if necessary, and to make it easier if I implement it myself.

**Comment by mweidling** [comment]
Taken from [minutes](https://github.com/OCR-D/ocrd-website/wiki/2020-08-20#api-and-ocr-d-butler):

"OCR-D API should be showcased in a self-contained docker container for further discussion and easy testing"

I'm not sure if this is still relevant, but I wanted to let you know, @joschrew .

**Comment by joschrew** [comment]
From my point of view this ticket has been divided into into the following two tickets:
https://github.com/OCR-D/zenhub/issues/99 and https://github.com/OCR-D/zenhub/issues/100 or in other words if this two tickets are done we have the reference implementation. Maybe I am wrong with what I just wrote, but if not we have redundant Tickets and should at least link properly or delete this one.
