### ISSUE TITLE
Provide docu (spec) about the workflow format decision

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#90]
**Describe the feature you'd like**
A documentation about how to provide workflow format via Web API. 

**Is your feature request related to a problem? Please describe.**
we have decided now to use NextFLow. We need this decision/ information in the specs.
**User story**

As a (user/developer/...) I need (what your feature does) in order to (what you want to achieve with the feature).
As a developer I want to know how to provide or reuse workflows toenable me to implement ocr-d due to my needs.

- [x] draft pr (Konstantin)
- [x] update specs

**Comment by kba** [comment]
Let's work on the draft in https://github.com/OCR-D/spec/pull/208

**Comment by lena-hinrichsen** [comment]
Even though there may be improvements coming, we may close this and use new issues or epics for new wishes about the Nextflow Docu ?

**Comment by kba** [comment]
Yes, see https://github.com/OCR-D/spec/issues/241 and also https://github.com/OCR-D/spec/pull/242
